#!/usr/bin/env python3
"""Build agent-rules source into per-agent artifacts.

python3 stdlib only. No PyYAML: frontmatter is authored by us and restricted to a
documented subset (scalars, block scalars, and simple lists).

    python3 build.py                # build dist/
    python3 build.py --lint-only    # validate without writing
    python3 build.py --verify-vendor # check vendor/books against the lockfile
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
VENDOR = ROOT / "vendor"
DIST = ROOT / "dist"
VERSION = (ROOT / "VERSION").read_text(encoding="utf-8").strip() if (ROOT / "VERSION").exists() else "0.0.0"

# Byte budgets. Claude can afford the full core; Codex shares a 32 KiB total doc
# budget with every project AGENTS.md, so its artifact is capped much harder.
# Raised from 16 KiB when the design-defaults layer was added. Every byte here is
# paid on every turn of every task, so treat an increase as a decision, not a fix:
# prefer moving content into a skill.
BUDGET_CLAUDE_CORE = 24576
# Codex shares one budget across global + every project AGENTS.md. Default is 32 KiB;
# install raises it to 64 KiB. 16 KiB here still leaves 16 KiB for project docs even
# if the config patch never ran.
BUDGET_CODEX = 18432
# Scoped rules load only on a path match, so this budget is far less precious than
# core's — raised when the AI/vector schema rules were added.
BUDGET_SCOPED_TOTAL = 24576
SKILL_DESC_MAX = 1536  # description + when_to_use, combined, per Claude's truncation

PREFIX_TOKEN = "@AIRULES_PREFIX@"  # substituted with the install path at install time

GENERATED = "<!-- GENERATED by build.py — DO NOT EDIT — edit src/ and rebuild. agent-rules {v} -->"

# Secrets / PII / stale-context scan. The repo is public.
FORBIDDEN = [
    (re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+"), "email address"),
    (re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"), "IP address"),
    (re.compile(r"\b20\d{2}-\d{2}-\d{2}\b"), "hardcoded absolute date"),
    (re.compile(r"\b(gh[pousr]_[A-Za-z0-9]{16,}|sk-[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{16})"), "credential"),
    (re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"), "private key"),
]
# Placeholders that look like the real thing but are not.
ALLOWED_SUBSTRINGS = ("<user>@<server-ip>", "user@host", "0.0.0.0", "127.0.0.1", "<dockerhub-user>")


class BuildError(Exception):
    pass


# ---------------------------------------------------------------- frontmatter


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Return (frontmatter, body). Supports `k: v`, `k: |` blocks, and `- ` lists."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 3)
    if end == -1:
        raise BuildError("unterminated frontmatter")
    raw, body = text[4:end], text[end + 5 :]

    data: dict = {}
    lines = raw.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        m = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if not m:
            raise BuildError(f"unparsable frontmatter line: {line!r}")
        key, value = m.group(1), m.group(2).strip()

        if value == "|":  # block scalar
            i += 1
            block: list[str] = []
            while i < len(lines) and (lines[i].startswith("  ") or not lines[i].strip()):
                block.append(lines[i][2:] if lines[i].startswith("  ") else "")
                i += 1
            data[key] = "\n".join(block).rstrip() + "\n"
            continue

        if value == "":  # possibly a list
            i += 1
            items: list[str] = []
            while i < len(lines) and re.match(r"^\s+-\s+", lines[i]):
                items.append(re.sub(r"^\s+-\s+", "", lines[i]).strip().strip("\"'"))
                i += 1
            data[key] = items
            continue

        data[key] = value.strip().strip("\"'")
        i += 1
    return data, body


def read_doc(path: Path) -> tuple[dict, str]:
    try:
        return parse_frontmatter(path.read_text(encoding="utf-8"))
    except BuildError as exc:
        raise BuildError(f"{path.relative_to(ROOT)}: {exc}") from exc


# ---------------------------------------------------------------------- lint


def scan_forbidden(path: Path, text: str, errors: list[str]) -> None:
    for pattern, label in FORBIDDEN:
        for match in pattern.finditer(text):
            hit = match.group(0)
            if any(a in match.string[max(0, match.start() - 20) : match.end() + 20] for a in ALLOWED_SUBSTRINGS):
                continue
            if hit in ALLOWED_SUBSTRINGS:
                continue
            line = text[: match.start()].count("\n") + 1
            errors.append(f"{path.relative_to(ROOT)}:{line}: {label} in a public repo: {hit!r}")


def check_shell_blocks(path: Path, text: str, errors: list[str]) -> None:
    """Catch the newline-eaten corruption seen in the source agent.md export."""
    # Narrow on purpose: these patterns only occur when newlines were eaten during an
    # export. A broad rule like \bfi[a-z]+\b matches "first" and "finally".
    suspicious = re.compile(
        r"(apt-get\s+\w+[a-z-]*sudo|sudo\s+\S+[a-z]sudo\b|\bdone[a-z]{2,}|"
        r"<server-ip>cd\b|>/dev/nullsudo|\bfi(sudo|cd|echo)\b)"
    )
    for block in re.findall(r"```(?:bash|sh)?\n(.*?)```", text, re.S):
        for match in suspicious.finditer(block):
            errors.append(
                f"{path.relative_to(ROOT)}: shell block looks newline-corrupted near {match.group(0)!r}"
            )


# --------------------------------------------------------------- collection


def load_layer(directory: Path) -> list[tuple[Path, dict, str]]:
    if not directory.is_dir():
        return []
    out = []
    for path in sorted(directory.glob("*.md")):
        fm, body = read_doc(path)
        out.append((path, fm, body.strip() + "\n"))
    return out


def slug(path: Path) -> str:
    return path.stem


# ----------------------------------------------------------------- renderers


def render_claude_core(core) -> str:
    parts = [GENERATED.format(v=VERSION), ""]
    for _path, _fm, body in core:
        parts.append(body.rstrip())
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def render_scoped_rule(fm: dict, body: str) -> str:
    paths = fm.get("paths") or []
    if not paths:
        raise BuildError("scoped rule has no `paths:` globs")
    lines = ["---", "paths:"]
    lines += [f'  - "{p}"' for p in paths]
    lines += ["---", "", GENERATED.format(v=VERSION), ""]
    return "\n".join(lines) + body.rstrip() + "\n"


def render_codex(core, scoped, skills) -> str:
    """Core inline (verbatim or hand-written digest) + soft pointers for the rest.

    Codex has no import syntax and no path scoping, so anything not inline here is
    only reachable if the model chooses to open the pointer path.
    """
    parts = [
        GENERATED.format(v=VERSION),
        "",
        "# Global engineering rules",
        "",
        "These apply to every project on this machine. Project AGENTS.md files add to them and",
        "win on conflict, except where a rule below says it cannot be overridden.",
        "",
    ]
    for _path, fm, body in core:
        if fm.get("codex") == "digest" and fm.get("digest"):
            parts.append(fm["digest"].rstrip())
        elif fm.get("codex") == "pointer":
            continue
        else:
            parts.append(body.rstrip())
        parts.append("")

    if scoped or skills:
        parts += [
            "---",
            "",
            "## Detailed rules — read the relevant file before acting",
            "",
            "These are not loaded automatically. Open the one that matches what you are about to",
            "touch. A copy also lives in the project's `.agent/rules/` where one has been set up.",
            "",
        ]
        for path, fm, _body in scoped:
            globs = " ".join((fm.get("paths") or [])[:2])
            parts.append(f"- {globs} -> {PREFIX_TOKEN}/dist/claude/rules/airules-{slug(path)}.md")
        for d in skills:
            parts.append(f"- skill `{d.name}` -> {PREFIX_TOKEN}/dist/skills/{d.name}/SKILL.md")
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def render_agents_generic(core, scoped) -> str:
    """agents.md-standard artifact for Cursor/Copilot/Zed — no byte pressure."""
    parts = [GENERATED.format(v=VERSION), "", "# Global engineering rules", ""]
    for _path, _fm, body in core:
        parts.append(body.rstrip())
        parts.append("")
    for path, fm, body in scoped:
        globs = ", ".join(fm.get("paths") or [])
        parts.append(f"<!-- applies to: {globs} -->")
        parts.append(body.rstrip())
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def render_claude_stub() -> str:
    return (
        f"{GENERATED.format(v=VERSION)}\n\n"
        "# Global rules\n\n"
        "House engineering rules load automatically from `~/.claude/rules/airules-*.md`.\n"
        "Book-derived design methodologies are installed as skills named `book-*`; house\n"
        "procedures as `idn-*`. Load at most one `book-*` skill per task.\n"
    )


# ------------------------------------------------------------- book skills


BOOK_SKILLS = {
    "book-refactoring": {
        "title": "Refactoring",
        "body": "refactoring",
        "attrib": "Refactoring by Martin Fowler",
        "refs": {"catalog.md": "refactoring-guru", "reference.md": "refactoring:full"},
        "conflicts": [
            ("book-legacy-code", "No tests? That skill wins — characterization tests come first."),
            ("book-clean-architecture", "Moving a dependency across a layer boundary is architecture, not refactoring."),
            ("codebase-design", "Designing a new interface is that skill. This one changes an existing one without changing behaviour."),
        ],
    },
    "book-legacy-code": {
        "title": "Working with legacy code",
        "body": "working-effectively-with-legacy-code",
        "attrib": "Working Effectively with Legacy Code by Michael Feathers",
        "refs": {"reference.md": "working-effectively-with-legacy-code:full"},
        "conflicts": [("book-refactoring", "Once a green suite exists, that skill takes over.")],
    },
    "book-domain-driven-design": {
        "title": "Domain-driven design",
        "body": "domain-driven-design-distilled",
        "attrib": "Domain-Driven Design Distilled by Vaughn Vernon",
        "refs": {"strategic.md": "domain-driven-design:full", "tactical.md": "implementing-domain-driven-design:full"},
        "conflicts": [
            ("book-clean-architecture", "DDD decides what the boundary is; Clean Architecture decides which way the arrow points across it."),
            ("book-data-intensive", "Once state crosses a service or durability boundary, that skill wins."),
        ],
    },
    "book-clean-architecture": {
        "title": "Clean architecture",
        "body": "clean-architecture",
        "attrib": "Clean Architecture by Robert C. Martin",
        "refs": {"reference.md": "clean-architecture:full"},
        "conflicts": [("book-enterprise-patterns", "That skill wins on how a mapper or repository is implemented inside a layer.")],
    },
    "book-enterprise-patterns": {
        "title": "Enterprise application patterns",
        "body": "patterns-of-enterprise-application-architecture",
        "attrib": "Patterns of Enterprise Application Architecture by Martin Fowler",
        "refs": {"reference.md": "patterns-of-enterprise-application-architecture:full"},
        "conflicts": [("book-clean-architecture", "Dependency direction is that skill's call.")],
    },
    "book-data-intensive": {
        "title": "Data-intensive systems",
        "body": "designing-data-intensive-applications",
        "attrib": "Designing Data-Intensive Applications by Martin Kleppmann",
        "refs": {"reference.md": "designing-data-intensive-applications:full"},
        "conflicts": [("book-production-reliability", "What happens when a dependency is down is that skill's call.")],
    },
    "book-production-reliability": {
        "title": "Production reliability",
        "body": "release-it",
        "attrib": "Release It! by Michael Nygard",
        "refs": {"reference.md": "release-it:full"},
        "conflicts": [("book-data-intensive", "Correctness of the data model is that skill's call.")],
    },
    "book-pragmatic-programmer": {
        "title": "Pragmatic programming",
        "body": "the-pragmatic-programmer",
        "attrib": "The Pragmatic Programmer by Hunt and Thomas",
        "refs": {"reference.md": "the-pragmatic-programmer:full"},
        "conflicts": [("any more specific book-* skill", "This one loses. It is a tiebreaker, not a tie.")],
    },
    "book-code-construction": {
        "title": "Code construction",
        "body": "code-complete",
        "attrib": "Code Complete by Steve McConnell",
        "refs": {"clean-code.md": "clean-code"},
        "conflicts": [("any more specific book-* skill", "This one loses. It is the fallback when nothing else matches.")],
    },
}

HOUSE_OVERRIDES = """## House overrides

These outrank anything above and are not from the book.

- Core rules 00-60 always win. This skill never authorises a merge, a force-push, a destructive
  command, or a "tests pass" claim you did not run.
- Never refactor or restructure code the user did not ask you to touch. If it is needed to make
  the requested change safely, say so and get a yes first.
- Test policy — when to write tests and how — belongs to the `tdd` skill, not to this one.
- Load at most one `book-*` skill per task. If a second seems relevant, name both, choose, say why
  in one line, and continue.

If you notice you have already applied guidance from another `book-*` skill in this session, say
so, name which one governs the file you are in, and stop applying the other.
"""


def book_source(spec: str) -> Path:
    """`slug` -> the mini file; `slug:full` -> the full file."""
    if spec.endswith(":full"):
        s = spec[: -len(":full")]
        return VENDOR / "books" / s / f"{s}.md"
    return VENDOR / "books" / spec / f"{spec}.mini.md"


def split_mini(text: str) -> tuple[str, str]:
    """Return (when_to_use, remaining_sections) from a vendored mini ruleset."""
    body = re.sub(r"^#\s+OBEY.*?\n", "", text, count=1).lstrip()
    m = re.search(r"^##\s+When to use\s*\n(.*?)(?=^##\s)", body, re.S | re.M)
    when = " ".join(m.group(1).split()) if m else ""
    rest = re.sub(r"^##\s+When to use\s*\n.*?(?=^##\s)", "", body, count=1, flags=re.S | re.M)
    return when, rest.strip() + "\n"


def build_book_skills(errors: list[str]) -> list[Path]:
    made: list[Path] = []
    for name, spec in BOOK_SKILLS.items():
        src = book_source(spec["body"])
        if not src.exists():
            errors.append(f"missing vendored book for {name}: {src.relative_to(ROOT)}")
            continue
        when, rest = split_mini(src.read_text(encoding="utf-8"))
        negative = "Do NOT use for unrelated work, and never load a second book-* skill in the same task."
        description = f"{when} {negative}".strip()
        if len(description) > SKILL_DESC_MAX:
            description = description[: SKILL_DESC_MAX - 1].rsplit(" ", 1)[0]

        conflicts = "\n".join(f"- **`{other}`** — {verdict}" for other, verdict in spec["conflicts"])
        out_dir = DIST / "skills" / name
        out_dir.mkdir(parents=True, exist_ok=True)

        refs = []
        for filename, ref_spec in spec["refs"].items():
            ref_src = book_source(ref_spec)
            if not ref_src.exists():
                errors.append(f"missing reference for {name}: {ref_src.relative_to(ROOT)}")
                continue
            shutil.copyfile(ref_src, out_dir / filename)
            refs.append(f"- `{filename}` — open for one entry; do not read whole.")

        doc = (
            "---\n"
            f"name: {name}\n"
            f"description: {description}\n"
            "---\n\n"
            f"# {spec['title']}\n\n"
            f"> Distilled from *{spec['attrib']}*. MIT-licensed ruleset vendored from\n"
            "> ciembor/agent-rules-books.\n\n"
            "## Conflicts\n\n"
            "Mutually exclusive with other `book-*` skills — one per task (core rule 60).\n\n"
            f"{conflicts}\n\n"
            f"{rest}\n"
            f"{HOUSE_OVERRIDES}\n"
            + ("\n## Deeper reference\n\n" + "\n".join(refs) + "\n" if refs else "")
        )
        (out_dir / "SKILL.md").write_text(doc, encoding="utf-8")
        made.append(out_dir)
    return made


# ------------------------------------------------------------------- driver


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def budget(label: str, path: Path, cap: int, errors: list[str]) -> dict:
    n = path.stat().st_size
    if n > cap:
        errors.append(f"{label}: {n} B exceeds the {cap} B budget (over by {n - cap} B)")
    return {"file": str(path.relative_to(ROOT)), "bytes": n, "budget": cap}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lint-only", action="store_true")
    ap.add_argument("--verify-vendor", action="store_true")
    args = ap.parse_args()

    errors: list[str] = []

    if args.verify_vendor:
        lock = VENDOR / "books.lock.json"
        if not lock.exists():
            print("no vendor/books.lock.json", file=sys.stderr)
            return 1
        data = json.loads(lock.read_text(encoding="utf-8"))
        for rel, want in sorted(data.get("files", {}).items()):
            p = VENDOR / "books" / rel
            if not p.exists():
                errors.append(f"vendored file missing: {rel}")
            elif sha256(p) != want:
                errors.append(f"vendored file modified: {rel}")
        for e in errors:
            print(f"ERROR {e}", file=sys.stderr)
        print("vendor verified" if not errors else f"{len(errors)} vendor error(s)")
        return 1 if errors else 0

    core = load_layer(SRC / "core")
    scoped = load_layer(SRC / "scoped")
    if not core:
        print("ERROR no src/core/*.md", file=sys.stderr)
        return 1

    for path, _fm, body in core + scoped:
        scan_forbidden(path, body, errors)
        check_shell_blocks(path, body, errors)
    for path in sorted(SRC.glob("skills/*/*.md")):
        text = path.read_text(encoding="utf-8")
        scan_forbidden(path, text, errors)
        check_shell_blocks(path, text, errors)
        fm, _ = parse_frontmatter(text)
        combined = len(str(fm.get("description", ""))) + len(str(fm.get("when_to_use", "")))
        if combined > SKILL_DESC_MAX:
            errors.append(f"{path.relative_to(ROOT)}: description+when_to_use is {combined} chars (max {SKILL_DESC_MAX})")

    if args.lint_only:
        for e in errors:
            print(f"ERROR {e}", file=sys.stderr)
        print("lint clean" if not errors else f"{len(errors)} lint error(s)")
        return 1 if errors else 0

    if DIST.exists():
        shutil.rmtree(DIST)
    (DIST / "claude" / "rules").mkdir(parents=True)
    (DIST / "codex").mkdir(parents=True)
    (DIST / "agents").mkdir(parents=True)
    (DIST / "skills").mkdir(parents=True)

    core_out = DIST / "claude" / "rules" / "airules-00-core.md"
    core_out.write_text(render_claude_core(core), encoding="utf-8")

    scoped_bytes = 0
    for path, fm, body in scoped:
        out = DIST / "claude" / "rules" / f"airules-{slug(path)}.md"
        try:
            out.write_text(render_scoped_rule(fm, body), encoding="utf-8")
        except BuildError as exc:
            errors.append(f"{path.relative_to(ROOT)}: {exc}")
            continue
        scoped_bytes += out.stat().st_size

    (DIST / "claude" / "CLAUDE.md").write_text(render_claude_stub(), encoding="utf-8")

    house_skill_dirs = sorted(d for d in (SRC / "skills").glob("*") if d.is_dir())
    for d in house_skill_dirs:
        shutil.copytree(d, DIST / "skills" / d.name)
    book_dirs = build_book_skills(errors)

    codex_out = DIST / "codex" / "AGENTS.md"
    codex_out.write_text(render_codex(core, scoped, house_skill_dirs + book_dirs), encoding="utf-8")
    (DIST / "agents" / "AGENTS.md").write_text(render_agents_generic(core, scoped), encoding="utf-8")

    budgets = [
        budget("dist/claude/rules/airules-00-core.md", core_out, BUDGET_CLAUDE_CORE, errors),
        budget("dist/codex/AGENTS.md", codex_out, BUDGET_CODEX, errors),
    ]
    if scoped_bytes > BUDGET_SCOPED_TOTAL:
        errors.append(f"scoped layer: {scoped_bytes} B exceeds the {BUDGET_SCOPED_TOTAL} B budget")

    artifacts = {
        str(p.relative_to(DIST)): {"sha256": sha256(p), "bytes": p.stat().st_size}
        for p in sorted(DIST.rglob("*"))
        if p.is_file()
    }
    (DIST / "MANIFEST.json").write_text(
        json.dumps(
            {
                "version": VERSION,
                "prefix_token": PREFIX_TOKEN,
                "budgets": budgets,
                "scoped_bytes": scoped_bytes,
                "skills": sorted(d.name for d in (DIST / "skills").glob("*") if d.is_dir()),
                "artifacts": artifacts,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    for e in errors:
        print(f"ERROR {e}", file=sys.stderr)
    if errors:
        print(f"\n{len(errors)} error(s) — dist/ written but not valid", file=sys.stderr)
        return 1

    print(f"built agent-rules {VERSION}")
    for b in budgets:
        print(f"  {b['file']}: {b['bytes']} / {b['budget']} B")
    print(f"  scoped layer: {scoped_bytes} / {BUDGET_SCOPED_TOTAL} B")
    print(f"  skills: {len(artifacts and [d for d in (DIST / 'skills').glob('*') if d.is_dir()])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
